"""Write docs/CATEGORY_TEMPLATES.md: what Stage B adds per category, from the rule constants themselves, plus one
example per category rendered for all three targets (so the document cannot drift from the code).

    python -m app.templates_doc --out ../docs/CATEGORY_TEMPLATES.md
"""
import argparse
import html
from pathlib import Path

from app.rendering import TARGETS, render_all, token_counts
from app.stage_a import rules as detect
from app.stage_a.detector import FeatureDetector
from app.stage_b import rules as b
from app.stage_b.optimizer import optimize

CATS = ["closed_qa", "information_extraction", "classification", "summarization", "coding"]
# (prompt, pasted text or None); the category is selected by the user so the template shows exactly
EXAMPLES = {
    "closed_qa": ("when did the eiffel tower open", "The Eiffel Tower opened in 1889 for the World's Fair."),
    "information_extraction": ("pull out the names of the people mentioned", "Marie Curie met Pierre Curie in Paris."),
    "classification": ("which of these are mammals: dolphin, shark, bat, eagle", None),
    "summarization": ("hey can you summarize this article for me",
                      "The city council voted on Monday to expand the bike lane network by 40 km over two years."),
    "coding": ("write a function that checks if a string is a palindrome", None),
}
EXTRA = {
    "classification": "B06 states the allowed labels it finds in the prompt (`Use only these labels: \"x\", \"y\".`); "
                      "a \"which of these ... are X\" question gets `\"yes\", \"no\"`; otherwise the label set is "
                      "recorded as unresolved. A yes/no question about one item gets `" + b.SINGLE_LABEL_FORMAT + "` "
                      "instead of the per-item format.",
    "coding": f"B05: no language named -> `Use {b.DEFAULT_LANGUAGE}.`; code supplied or attached -> "
              f"`{b.KEEP_LANGUAGE}`",
}


def build() -> str:
    det = FeatureDetector()
    lines = ["# Category templates\n",
             "Generated by `python -m app.templates_doc` from the Stage B rule constants (`backend/app/stage_b/"
             "rules.py`); do not edit by hand. Stage B adds these only when the prompt does not already state them, "
             f"and only when the category is reliable (Stage A confidence >= {b.CATEGORY_MIN_CONFIDENCE}, or chosen "
             "by the user). Below the gate, B08 adds the text-group template when closed_qa + "
             "information_extraction + summarization together reach it and text is attached: "
             f"`{b.GROUP_BOTH}`. Otherwise the prompt goes to Stage C for the category.\n",
             "Every category also gets the clean-up rules (B07 structure, B01 filler, B02 repetition) and, with an "
             "attachment, the attachment rule for its type (B09-B15).\n",
             "| category | output format (B03) | length (B04) | other | constraints Stage A checks |",
             "|---|---|---|---|---|"]
    for c in CATS:
        lines.append(f"| {c} | {b.FORMAT_DEFAULTS[c]} | {b.LENGTH_DEFAULTS.get(c, '-')} | "
                     f"{EXTRA.get(c, '-')} | {', '.join(detect.RELEVANT_CONSTRAINTS[c]) or '-'} |")
    lines.append("")
    for c in CATS:
        prompt, text = EXAMPLES[c]
        out = optimize(prompt, det.detect(prompt, text), category=c, separate_text=text is not None)
        rendered = render_all(out.ir, context_text=text)
        tokens = token_counts(rendered)
        lines += [f"## {c}\n", f"Prompt: `{prompt}`" + (f", with pasted text: `{text}`" if text else "") + "  ",
                  f"Rules applied: {', '.join(out.rules_applied)}\n",
                  "| target | input tokens | rendering |", "|---|---|---|"]
        for t in TARGETS:
            cell = html.escape(rendered[t]).replace("|", "&#124;").replace("\n", "<br>")
            label = f"{tokens[t]['tokens']} " + ("(exact, tiktoken)" if tokens[t]["exact"] else "(approx., chars/4)")
            lines.append(f"| {t} | {label} | <pre>{cell}</pre> |")
        lines.append("")
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", type=Path)
    args = ap.parse_args()
    text = build()
    print(text)
    if args.out:
        args.out.write_text(text, encoding="utf-8")


if __name__ == "__main__":
    main()
